[workspace]
channels = ["conda-forge", "avcopan"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
autopilot = { path = "." }
automol = "==0.0.6"
automech-autostore = "==0.0.4"
crest = ">=3.0.2"
xtb = ">=6.7.1"
libgfortran = ">=14,<15"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
qcio = "*"
qcop = "*"
prism-pruner = ">=0.1.0, <0.2"

[package]
name = "autopilot"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.config]
ignore-pyproject-manifest = false
ignore-pypi-mapping = false

[feature.dev.dependencies]
uv = "*"
ruff = "*"
ty = "*"
import-linter = "*"
pytest = "*"
pytest-cov = "*"
lefthook = "*"
rattler-build = "*"
tbump = "*"
ipykernel = "*"

[feature.docs.dependencies]
sphinx = "*"
myst-parser = "*"
pydata-sphinx-theme = "*"
sphinx-autodoc2 = "*"

[feature.local.pypi-dependencies]
automol = { path = "../automol", editable = true }
automech-autostore = { path = "../autostore", editable = true }
prism-pruner = { path = "../prism_pruner", editable = true }

[feature.local.pypi-options.dependency-overrides]
automol = { path = "../automol", editable = true }
automech-autostore = { path = "../autostore", editable = true }
prism-pruner = { path = "../prism_pruner", editable = true }

[environments]
default = { solve-group = "default" }
dev = { features = ["dev", "docs"], solve-group = "default"}
dev-local = { features = ["dev", "docs", "local"] }

[feature.dev.tasks]
# Manage pyproject.toml with uv
uv = "uv"
add = "uv add"
remove = "uv remove"
# Individual tasks for pre-commit hooks (must be added to lefthook.yaml)
fmt = "ruff format ."
lint = "ruff check . --fix"
types = "ty check"
imports = "lint-imports"
test = "pytest"
# Run pre-commit hooks (see lefthook.yaml)
pre-commit = "lefthook run pre-commit --all-files --fail-on-changes"
# Build and view documentation
docs-build = "sphinx-build docs/source docs/build"
docs-view = { cmd = "scripts/view-docs.sh", depends-on = ["docs-build"] }
# Build and publish conda package
build-conda = "pixi build -o dist"
publish-conda = "rattler-build upload anaconda dist/*.conda -o avcopan"
# Build and publish PyPI package
build-pypi = "uv build"
publish-pypi = "uv publish"
publish-test-pypi = "uv publish --publish-url https://test.pypi.org/legacy/"
# Initiate release
version = "tbump current-version"
release = "tbump"
# Setup and initialize this repository (only run once)
setup = "./scripts/setup.sh"
init = { cmd = "./scripts/init.sh", depends-on = ["setup"]}

[feature.local.tasks]
test-automol = "pytest ../automol/tests"
test-autostore = "pytest ../autostore/tests"
test-autopilot = "pytest tests"
